server:
  port: ${PORT:8888}

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vargasroc/esp-back-i-parcial
          default-label: develop
          force-pull: true
          search-paths: config-data