server:
  port: ${PORT:0}
spring:
  application:
    name: api-movie
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: usr-movie
    password: pwd-movie
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}